add version text, root user check and application check

diff --git a/bin/hello-world b/bin/hello-world
--- a/bin/hello-world
+++ b/bin/hello-world
@@ -1,5 +1,41 @@
 #!/bin/bash
 
+# An hello world app.
+#
+# @author    Björn Hempel <bjoern@hempel.li>
+# @version   1.0 (2017-07-05)
+#
+# @copyright MIT License
+# @copyright
+# @copyright Copyright (c) 2017 Björn Hempel
+# @copyright
+# @copyright Permission is hereby granted, free of charge, to any person obtaining a copy
+# @copyright of this software and associated documentation files (the "Software"), to deal
+# @copyright in the Software without restriction, including without limitation the rights
+# @copyright to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# @copyright copies of the Software, and to permit persons to whom the Software is
+# @copyright furnished to do so, subject to the following conditions:
+# @copyright
+# @copyright The above copyright notice and this permission notice shall be included in all
+# @copyright copies or substantial portions of the Software.
+# @copyright
+# @copyright THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# @copyright IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# @copyright FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# @copyright AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# @copyright LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# @copyright OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# @copyright SOFTWARE.
+# @copyright
+# @copyright Written by Björn Hempel <bjoern@hempel.li>.
+# ------------
+
+# some needed applications
+applications=()
+
+# some config
+checkRootUser=false
+
 # makes the regexp search case insensitive
 shopt -s nocasematch
 
@@ -26,12 +62,33 @@ fi
 # because we are inside the bin folder
 pathRoot=$(dirname "$pathRoot")
 
-# include friends of bash
-source "$FRIENDS_OF_BASH_SOURCE_FILE"
-
 # include arguments
 source "$pathRoot/lib/arguments"
 
-# header
-log "header" "Hello world! :)"
+# check the current used user
+if $checkRootUser; then
+    userId=$(id -u)
 
+    if [[ $userId -ne 0 ]]; then
+        echo "Please run this script as root."
+        echo "sudo $0 ..."
+        exit 1
+    fi
+fi
+
+# check applications
+for application in "${applications[@]}"; do
+    which $application >/dev/null
+
+    if [ "$?" -gt "0" ]; then
+        echo "Application \"$application\" is not installed. Please install it before continuing. Abort.."
+        exit
+    fi
+done
+
+# check parameter count
+if [ "${#PARAMETERS[@]}" -lt 1 ]; then
+    log "header" "Hello world! :) (no parameter given)"
+else
+    log "header" "Hello world! :) (first parameter: \"${PARAMETERS[0]}\")"
+fi
