Add version checker; #2

diff --git a/bin/hello-world b/bin/hello-world
--- a/bin/hello-world
+++ b/bin/hello-world
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# ------------
 # An hello world app.
 #
 # @author    Björn Hempel <bjoern@hempel.li>
@@ -65,6 +66,14 @@ pathRoot=$(dirname "$pathRoot")
 # include arguments
 source "$pathRoot/lib/arguments"
 
+# check installed friends of library apps
+message=$(checkCurrentVersionNumbers "$pathRoot/.require")
+lastStatus=$?
+if [ $lastStatus -gt 0 ]; then
+    echo "$message Abort.."
+    exit 1
+fi
+
 # check the current used user
 if $checkRootUser; then
     userId=$(id -u)
@@ -82,7 +91,7 @@ for application in "${applications[@]}"; do
 
     if [ "$?" -gt "0" ]; then
         echo "Application \"$application\" is not installed. Please install it before continuing. Abort.."
-        exit
+        exit 1
     fi
 done
 
